import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

const dellIcon = "/assets/dell-logo.png";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} prevent-select`}>
        <div>
          <Image
            src={dellIcon}
            width={300}
            height={300}
            className="absolute top-10 left-10 z-10"
          />
          {children}
        </div>
      </body>
    </html>
  );
}
